import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const questions=[
{id:'period',label:'първа глава',title:'Кога беше част от „Дъга“?',hint:'Избери периода, който най-добре те описва.',type:'choice',options:['1993–1999','2000–2007','2008–2014','През повече от един период']},
{id:'first_memory',label:'първи спомен',title:'Кой е първият спомен, който изниква, когато чуеш „Дъга“?',hint:'Едно изречение е напълно достатъчно. Може да е човек, място, игра или някоя беля.',placeholder:'Например: миризмата на темперите в занималнята…',type:'textarea'},
{id:'three_words',label:'три думи',title:'Ако трябва да опишеш „Дъга“ с три думи — кои ще са те?',hint:'Първите три, които ти идват. Не мисли много.',placeholder:'Твоите три думи…',type:'text'},
{id:'people',label:'хората',title:'Има ли човек от „Дъга“, с когото животът те среща и до днес?',hint:'Може да напишеш име, кратка история или просто „да“.',placeholder:'Разкажи ни…',type:'textarea'},
{id:'legacy',label:'това, което остава',title:'Какво ти даде „Дъга“, което носиш със себе си и днес?',hint:'Тук няма грешен отговор. Търсим онова малко нещо, което е останало.',placeholder:'Може би навик, човек, урок или чувство…',type:'textarea'},
{id:'return_day',label:'ако можеше',title:'Ако можеше да се върнеш за един ден като дете — какво би направил първо?',hint:'Представи си, че утре сутрин отново си там.',placeholder:'Утре сутрин отваряш вратата…',type:'textarea'},
{id:'message',label:'последна дума',title:'Какво би казал на децата, които днес започват своята история в „Дъга“?',hint:'Този отговор може един ден да бъде прочетен от някое от тях. ❤️',placeholder:'Остави им няколко думи…',type:'textarea'}
];

function Rainbow({progress=0}){return <svg className="rainbow" viewBox="0 0 180 90" aria-hidden="true"><path className="arc a1" pathLength="1" style={{strokeDashoffset:1-progress}} d="M10 82 A80 80 0 0 1 170 82"/><path className="arc a2" pathLength="1" style={{strokeDashoffset:1-progress}} d="M22 82 A68 68 0 0 1 158 82"/><path className="arc a3" pathLength="1" style={{strokeDashoffset:1-progress}} d="M34 82 A56 56 0 0 1 146 82"/><path className="arc a4" pathLength="1" style={{strokeDashoffset:1-progress}} d="M46 82 A44 44 0 0 1 134 82"/></svg>}
function Doodles(){return <><span className="doodle heart">♡</span><span className="doodle sun">☼</span><span className="doodle star">✦</span><span className="doodle flower">✿</span><span className="line-doodle">〰</span></>}
function App(){
 const [started,setStarted]=useState(false),[index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[consent,setConsent]=useState(false),[sending,setSending]=useState(false),[submitted,setSubmitted]=useState(false),[error,setError]=useState(false);
 const q=questions[index]; const value=answers[q?.id]||''; const setValue=v=>setAnswers(a=>({...a,[q.id]:v}));
 const next=()=>{if(!value.trim())return;if(index<questions.length-1){setIndex(i=>i+1);setError(false)}else submit()};
 const back=()=>{if(index>0)setIndex(i=>i-1);else setStarted(false)};
 async function submit(){setSending(true);setError(false);try{const key=import.meta.env.VITE_WEB3FORMS_ACCESS_KEY;if(!key)throw new Error('missing');const form=new FormData();form.append('access_key',key);form.append('subject','Нова история от „Дъга“');Object.entries(answers).forEach(([k,v])=>form.append(k,v));form.append('consent',consent?'Да':'Не');form.append('timestamp',new Date().toISOString());form.append('source','Duga Memory Experience');const r=await fetch('https://api.web3forms.com/submit',{method:'POST',body:form});if(!r.ok)throw new Error('network');const data=await r.json();if(!data.success)throw new Error('submit');setSubmitted(true)}catch(e){setError(true)}finally{setSending(false)}}
 if(submitted)return <main className="page final"><Doodles/><Rainbow progress={1}/><div className="final-mark">🌈</div><p className="eyebrow">това беше нашето малко пътуване</p><h1>Благодарим ти,<br/><em>че се върна.</em></h1><p className="lead">Някои истории започват в „Дъга“,<br/>но никога не свършват.</p><div className="meet"><span>Ще се видим отново</span><strong>10 октомври · 11:00</strong><small>в двора на детската градина</small></div><p className="signature">С обич,<br/><b>Силвия Георгиева и екипът на „Дъга“</b></p></main>;
 if(!started)return <main className="page intro"><Doodles/><div className="logo">ДЪГА</div><p className="eyebrow">едно малко пътуване назад</p><h1>Някои места<br/><em>остават</em> завинаги.</h1><p className="lead">Ако „Дъга“ е част от твоята история,<br/>имаме няколко въпроса за теб.<br/><span>Няма правилни отговори. Само истински спомени.</span></p><button className="primary" onClick={()=>setStarted(true)}>Да си припомним <span>→</span></button><p className="tiny">Отнема около 2 минути</p><div className="intro-rainbow"><Rainbow progress={1}/></div></main>;
 return <main className="page journey"><Doodles/><header><button className="back" onClick={back} aria-label="Назад">←</button><div className="counter">{String(index+1).padStart(2,'0')} / {String(questions.length).padStart(2,'0')}</div><Rainbow progress={(index+1)/questions.length}/></header><section className="scene" key={q.id}><p className="eyebrow">{q.label}</p><h2>{q.title}</h2><p className="hint">{q.hint}</p>{q.type==='choice'?<div className="choices">{q.options.map((o,i)=><button key={o} className={value===o?'selected':''} onClick={()=>setValue(o)}><span>{String.fromCharCode(65+i)}</span>{o}{value===o&&<b>✓</b>}</button>)}</div>:<div className="field-wrap"><textarea autoFocus={q.type==='textarea'} value={value} onChange={e=>setValue(e.target.value)} placeholder={q.placeholder} rows={5} aria-label={q.title}/></div>}<div className="actions"><button className="next" disabled={!value.trim()||sending} onClick={next}>{sending?'Запазваме спомена…':index===questions.length-1?'Запази спомена':'Напред'} <span>→</span></button>{index===questions.length-1&&<label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Съгласявам се моят отговор да бъде използван като анонимен цитат в комуникацията на „Дъга“.</label>}{error&&<p className="error">Май дъгата прекъсна за момент. Провери връзката си и опитай отново.</p>}</div></section></main>
}
createRoot(document.getElementById('root')).render(<App/>);
